# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6903706898ec39f449056fd1867e00d8d96f9540daea696555f2c08ca6fff33036560f4b8fb02543277e1a48550615f33244f0b927ee323c63be4481aada1f0a

test:
  secret_key_base: 80972dd051737c0ac598cb14d6343ad0a6f4c1f95f121aa833b099644ed944f99265af31598d8e140487a65a08218ea6106a3b85ac4041b13c1b7a9df684d2bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
